name: Release
on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
  
    - name: Checkout Code
      uses: actions/checkout@v3
  
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    
    - name: Build Package
      run: make package
    
    - name: Unload Signing Stores
      env:
        SIGNING_STORE: ${{ secrets.SIGNING_STORE }}
        SIGNING_STORE_OLD: ${{ secrets.SIGNING_STORE_OLD }}
      run: |
        echo $SIGNING_STORE | base64 --decode > signingstore.jks
        echo $SIGNING_STORE_OLD | base64 --decode > signingstore_old.jks

    - name: Sign Package
      env:
        STORE_PASS: ${{ secrets.STORE_PASS }}
      run: |
        make sign
    
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: CrowdSec.zip
